# Quetty Base Configuration File
# Default base configuration for all profiles
# For detailed configuration reference, see: docs/CONFIGURATION.md

# =============================================================================
# APPLICATION CONFIGURATION
# =============================================================================

# Number of messages displayed per page (1-1000)
page_size = 100

# Interval for peeking at new messages (seconds)
peek_interval = 1

# Timeout for individual polling operations (milliseconds)
poll_timeout_ms = 10

# UI refresh interval for animations and loading indicators (milliseconds)
tick_interval_millis = 250

# =============================================================================
# DEAD LETTER QUEUE (DLQ) CONFIGURATION
# =============================================================================

# Timeout for receiving messages from DLQ (seconds, 1-60)
dlq_receive_timeout_secs = 10

# Timeout for sending messages to main queue (seconds, 1-60)
dlq_send_timeout_secs = 10

# Maximum retry attempts for DLQ operations (1-100)
dlq_max_attempts = 10

# Maximum total time for entire DLQ operation including all retries (seconds)
dlq_overall_timeout_cap_secs = 60

# Hard cap for DLQ receive timeouts (seconds)
dlq_receive_timeout_cap_secs = 10

# Hard cap for DLQ send timeouts (seconds)
dlq_send_timeout_cap_secs = 15

# Delay between DLQ operation retry attempts (milliseconds)
dlq_retry_delay_ms = 500

# =============================================================================
# INPUT/UI CONFIGURATION
# =============================================================================

# Polling interval for keyboard input detection (milliseconds)
crossterm_input_listener_interval_ms = 20

# Number of retries for input listener operations
crossterm_input_listener_retries = 5

# Duration between animation frames for loading indicators (milliseconds)
ui_loading_frame_duration_ms = 100

# =============================================================================
# BULK OPERATIONS CONFIGURATION
# =============================================================================

# Maximum number of messages processed in a single batch operation (1-1000)
max_batch_size = 200

# Maximum total messages allowed in any bulk operation (safety limit)
max_messages_to_process = 10000

# Global timeout for bulk operations (seconds)
operation_timeout_secs = 300

# =============================================================================
# QUEUE STATISTICS CONFIGURATION
# =============================================================================

# Enable/disable queue statistics display
queue_stats_display_enabled = true

# Cache duration for queue statistics in seconds (0 = no caching)
queue_stats_cache_ttl_seconds = 60

# =============================================================================
# THEME CONFIGURATION
# =============================================================================
[theme]
# Theme family: "nightfox", "catppuccin", "quetty"
theme_name = "nightfox"

# Theme variant within the family
# Nightfox: "nightfox", "duskfox", "dawnfox", "nordfox", "terafox", "carbonfox"
# Catppuccin: "mocha", "macchiato", "frappe", "latte"
# Quetty: "dark", "light"
flavor_name = "duskfox"

# =============================================================================
# AUTHENTICATION CONFIGURATION
# =============================================================================
[auth]
# Primary authentication method: "connection_string" or "azure_ad"
method = "azure_ad"

# =============================================================================
# SERVICE BUS CONFIGURATION
# =============================================================================
[servicebus]
# Azure Service Bus connection string
# Format: "Endpoint=sb://namespace.servicebus.windows.net/;SharedAccessKeyName=...;SharedAccessKey=..."
# SECURITY: Use environment variables SERVICEBUS__ENCRYPTED_CONNECTION_STRING and SERVICEBUS__ENCRYPTION_SALT instead of storing here
# connection_string = ""

# =============================================================================
# AZURE AD CONFIGURATION
# =============================================================================
[azure_ad]
# Authentication method:
# - "device_code": Interactive device code flow (recommended for CLI)
# - "client_secret": Service principal with client secret (for automation)
auth_method = "device_code"

# Azure AD Configuration (use environment variables for security)
# tenant_id = ""       # Set via AZURE_AD__TENANT_ID environment variable
# client_id = ""       # Set via AZURE_AD__CLIENT_ID environment variable
# client_secret = ""   # Set via AZURE_AD__CLIENT_SECRET (client_secret only)
#                      # Or use encrypted: AZURE_AD__ENCRYPTED_CLIENT_SECRET + AZURE_AD__ENCRYPTION_SALT

# Azure Resource Information (optional - auto-discovered if not specified)
# subscription_id = "" # Set via AZURE_AD__SUBSCRIPTION_ID environment variable
# resource_group = ""  # Set via AZURE_AD__RESOURCE_GROUP environment variable
# namespace = ""       # Set via AZURE_AD__NAMESPACE environment variable

# Azure Authority Configuration (optional - for sovereign clouds)
# authority_host = "https://login.microsoftonline.com"  # Default
# scope = "https://servicebus.azure.net/.default"       # Default

# =============================================================================
# LOGGING CONFIGURATION
# =============================================================================
[logging]
# Log level: "trace", "debug", "info", "warn", "error"
level = "info"

# Log file path (optional - if not specified, uses smart defaults)
# Development builds: logs/quetty.log (for easy access)
# Production builds: ~/.cache/quetty/logs/quetty.log (OS standard)
# file = "custom-path/quetty.log"

# Maximum log file size in MB before rotation (default: 10)
# max_file_size_mb = 10

# Maximum number of backup log files to keep (default: 5)
# max_backup_files = 5

# Whether to clean up old log files on startup (default: true)
# cleanup_on_startup = true

# =============================================================================
# ENVIRONMENT VARIABLE REFERENCE
# =============================================================================
# You can override any configuration value using environment variables:
# Format: SECTION__KEY (double underscore)
#
# Examples:
# export QUETTY_PAGE_SIZE=50
# export THEME__THEME_NAME="catppuccin"
# export THEME__FLAVOR_NAME="mocha"
# Auth method is configured in config.toml azure_ad.auth_method, not via environment variable
# export AZURE_AD__TENANT_ID="your-tenant-id"
# export AZURE_AD__CLIENT_ID="your-client-id"
# export AZURE_AD__CLIENT_SECRET="your-client-secret"
# export AZURE_AD__ENCRYPTED_CLIENT_SECRET="<encrypted-client-secret>"  # Alternative to plain client secret
# export AZURE_AD__ENCRYPTION_SALT="<salt-for-client-secret-encryption>"
# export SERVICEBUS__ENCRYPTED_CONNECTION_STRING="<encrypted-connection-string>"  # UI requires encrypted connection strings
# export SERVICEBUS__ENCRYPTION_SALT="<salt-for-connection-string-encryption>"
# export LOGGING__LEVEL="debug"
# export LOGGING__FILE="debug.log"
# export LOGGING__MAX_FILE_SIZE_MB=50
# export LOGGING__MAX_BACKUP_FILES=10
# export LOGGING__CLEANUP_ON_STARTUP=false
#
# For detailed configuration documentation, see: docs/CONFIGURATION.md
