# Dawnfox - A warm light theme inspired by the rose-pine theme
# Inspired by: https://github.com/EdenEast/nightfox.nvim
[metadata]
name = "Dawnfox"
description = "A warm light theme inspired by the rose-pine theme"
author = "EdenEast (Nightfox.nvim)"
theme_name = "nightfox"
flavor_name = "dawnfox"
theme_icon = "🦊"
flavor_icon = "🌅"
inspiration = "https://github.com/EdenEast/nightfox.nvim"

[colors]
# === Core Text Colors ===
text_primary = "#575279" # Primary text throughout app
text_muted = "#9893a5"   # Muted text for help bar separators

# === Layout Colors ===
surface = "#f2e9e1" # Surface background for pickers

# === Accent Colors ===
primary_accent = "#286983" # Blue - focused borders, active states, status text
title_accent = "#575279"   # Primary text - component titles
header_accent = "#56949f"  # Teal - table headers and line numbers

# === Selection Colors ===
selection_bg = "#d7827e" # Rose - selection background
selection_fg = "#faf4ed" # Light text - selection foreground

# === Message Table Colors ===
message_sequence = "#ea9d34"       # Gold - sequence numbers
message_id = "#b4637a"             # Red/Rose - message identifiers
message_timestamp = "#56949f"      # Teal - timestamps
message_delivery_count = "#d7827e" # Rose - delivery counts
message_state_ready = "#56949f"    # Teal - Ready for delivery (Active, Scheduled)
message_state_deferred = "#ea9d34" # Gold - Deferred handling (Deferred)
message_state_outcome = "#d7827e"  # Rose - Processing outcome (Completed, Abandoned)
message_state_failed = "#b4637a"   # Red/Rose - Failed delivery (Dead-lettered)
queue_count = "#56949f"            # Teal - for queue counts (legacy field)

# === List Item Colors ===
namespace_list_item = "#d7827e" # Rose - namespace picker items

# === Status Colors ===
status_success = "#56949f" # Teal - success messages
status_warning = "#ea9d34" # Gold - warning messages
status_error = "#b4637a"   # Red/Rose - error messages
status_info = "#286983"    # Blue - queue picker items
status_loading = "#d7827e" # Rose - loading indicator

# === Help System Colors ===
shortcut_key = "#ea9d34"         # Gold - keyboard shortcuts
shortcut_description = "#9893a5" # Muted text - help descriptions
help_section_title = "#d7827e"   # Rose - help section titles

# === Popup System Colors (used by confirmation popup) ===
popup_background = "#fffaf3" # Slightly different from main bg
popup_text = "#9893a5"       # Muted text - secondary text
