# Catppuccin Frappé - A less vibrant alternative using subdued colors for a muted aesthetic
[metadata]
name = "Catppuccin Frappé"
description = "A less vibrant alternative using subdued colors for a muted aesthetic"
author = "Catppuccin Community"
theme_name = "catppuccin"
flavor_name = "frappe"
theme_icon = "😸"
flavor_icon = "🪴"
inspiration = "https://github.com/catppuccin/catppuccin"

[colors]
# === Core Text Colors ===
text_primary = "#c6d0f5" # Text - primary text throughout app
text_muted = "#a5adce"   # Subtext0 - help bar separators

# === Layout Colors ===
surface = "#414559" # Surface0 - background for pickers

# === Accent Colors ===
primary_accent = "#8caaee" # Blue - focused borders, active states, status text
title_accent = "#c6d0f5"   # Text - component titles
header_accent = "#a6d189"  # Green - table headers and line numbers

# === Selection Colors ===
selection_bg = "#ca9ee6" # Mauve - selection background
selection_fg = "#303446" # Base - selection foreground

# === Message Table Colors ===
message_sequence = "#e5c890"       # Yellow - sequence numbers
message_id = "#e78284"             # Red - message identifiers
message_timestamp = "#99d1db"      # Sky - timestamps
message_delivery_count = "#ca9ee6" # Mauve - delivery counts
message_state_ready = "#a6d189"    # Green - Ready for delivery (Active, Scheduled)
message_state_deferred = "#e5c890" # Yellow - Deferred handling (Deferred)
message_state_outcome = "#ca9ee6"  # Mauve - Processing outcome (Completed, Abandoned)
message_state_failed = "#e78284"   # Red - Failed delivery (Dead-lettered)
queue_count = "#a6d189"            # Green - for queue counts (legacy field)

# === List Item Colors ===
namespace_list_item = "#ca9ee6" # Mauve - namespace picker items

# === Status Colors ===
status_success = "#a6d189" # Green - success messages
status_warning = "#e5c890" # Yellow - warning messages
status_error = "#e78284"   # Red - error messages
status_info = "#99d1db"    # Sky - queue picker items
status_loading = "#ca9ee6" # Mauve - loading indicator

# === Help System Colors ===
shortcut_key = "#e5c890"         # Yellow - keyboard shortcuts
shortcut_description = "#a5adce" # Subtext0 - help descriptions
help_section_title = "#ca9ee6"   # Mauve - help section titles

# === Popup System Colors (used by confirmation popup) ===
popup_background = "#292c3c" # Mantle - slightly different from main bg
popup_text = "#a5adce"       # Subtext0 - secondary text
