# Duskfox - A dark theme inspired by the rose-pine theme
# Inspired by: https://github.com/EdenEast/nightfox.nvim
[metadata]
name = "Duskfox"
description = "A dark theme inspired by the rose-pine theme"
author = "EdenEast (Nightfox.nvim)"
theme_name = "nightfox"
flavor_name = "duskfox"
theme_icon = "🦊"
flavor_icon = "🌆"
inspiration = "https://github.com/EdenEast/nightfox.nvim"

[colors]
# === Core Text Colors ===
text_primary = "#e0def4" # Primary text throughout app
text_muted = "#6e6a86"   # Muted text for help bar separators

# === Layout Colors ===
surface = "#2d2a45" # Surface background for pickers

# === Accent Colors ===
primary_accent = "#569fba" # Blue - focused borders, active states, status text
title_accent = "#e0def4"   # Primary text - component titles
header_accent = "#a3be8c"  # Green - table headers and line numbers

# === Selection Colors ===
selection_bg = "#eb6f92" # Rose - selection background
selection_fg = "#232136" # Dark text - selection foreground

# === Message Table Colors ===
message_sequence = "#f6c177"       # Gold - sequence numbers  
message_id = "#ea9a97"             # Red/Rose - message identifiers
message_timestamp = "#9ccfd8"      # Foam - timestamps
message_delivery_count = "#eb6f92" # Rose - delivery counts
message_state_ready = "#a3be8c"    # Green - Ready for delivery (Active, Scheduled)
message_state_deferred = "#f6c177" # Gold - Deferred handling (Deferred)
message_state_outcome = "#eb6f92"  # Rose - Processing outcome (Completed, Abandoned)
message_state_failed = "#ea9a97"   # Red/Rose - Failed delivery (Dead-lettered)
queue_count = "#a3be8c"            # Green - for queue counts (legacy field)

# === List Item Colors ===
namespace_list_item = "#eb6f92" # Rose - namespace picker items

# === Status Colors ===
status_success = "#a3be8c" # Green - success messages
status_warning = "#f6c177" # Gold - warning messages
status_error = "#ea9a97"   # Red/Rose - error messages
status_info = "#9ccfd8"    # Foam - queue picker items
status_loading = "#eb6f92" # Rose - loading indicator

# === Help System Colors ===
shortcut_key = "#f6c177"         # Gold - keyboard shortcuts
shortcut_description = "#6e6a86" # Muted text - help descriptions
help_section_title = "#eb6f92"   # Rose - help section titles

# === Popup System Colors (used by confirmation popup) ===
popup_background = "#1f1d2e" # Slightly different from main bg
popup_text = "#6e6a86"       # Muted text - secondary text 