# Nordfox - A nord-esque colorscheme
# Inspired by: https://github.com/EdenEast/nightfox.nvim
[metadata]
name = "Nordfox"
description = "A nord-esque colorscheme"
author = "EdenEast (Nightfox.nvim)"
theme_name = "nightfox"
flavor_name = "nordfox"
theme_icon = "🦊"
flavor_icon = "🏔️"
inspiration = "https://github.com/EdenEast/nightfox.nvim"

[colors]
# === Core Text Colors ===
text_primary = "#cdcecf" # Primary text throughout app
text_muted = "#60728a"   # Muted text for help bar separators

# === Layout Colors ===
surface = "#3b4252" # Surface background for pickers

# === Accent Colors ===
primary_accent = "#81a1c1" # Blue - focused borders, active states, status text
title_accent = "#cdcecf"   # Primary text - component titles
header_accent = "#a3be8c"  # Green - table headers and line numbers

# === Selection Colors ===
selection_bg = "#bf616a" # Red - selection background
selection_fg = "#2e3440" # Dark text - selection foreground

# === Message Table Colors ===
message_sequence = "#ebcb8b"       # Yellow - sequence numbers
message_id = "#bf616a"             # Red - message identifiers
message_timestamp = "#88c0d0"      # Light blue - timestamps
message_delivery_count = "#b48ead" # Purple - delivery counts
message_state_ready = "#a3be8c"    # Green - Ready for delivery (Active, Scheduled)
message_state_deferred = "#ebcb8b" # Yellow - Deferred handling (Deferred)
message_state_outcome = "#b48ead"  # Purple - Processing outcome (Completed, Abandoned)
message_state_failed = "#bf616a"   # Red - Failed delivery (Dead-lettered)
queue_count = "#a3be8c"            # Green - for queue counts (legacy field)

# === List Item Colors ===
namespace_list_item = "#b48ead" # Purple - namespace picker items

# === Status Colors ===
status_success = "#a3be8c" # Green - success messages
status_warning = "#ebcb8b" # Yellow - warning messages
status_error = "#bf616a"   # Red - error messages
status_info = "#88c0d0"    # Light blue - queue picker items
status_loading = "#b48ead" # Purple - loading indicator

# === Help System Colors ===
shortcut_key = "#ebcb8b"         # Yellow - keyboard shortcuts
shortcut_description = "#60728a" # Muted text - help descriptions
help_section_title = "#b48ead"   # Purple - help section titles

# === Popup System Colors (used by confirmation popup) ===
popup_background = "#2e3440" # Slightly different from main bg
popup_text = "#60728a"       # Muted text - secondary text
