# Terafox - A greenish colorscheme
# Inspired by: https://github.com/EdenEast/nightfox.nvim
[metadata]
name = "Terafox"
description = "A greenish colorscheme"
author = "EdenEast (Nightfox.nvim)"
theme_name = "nightfox"
flavor_name = "terafox"
theme_icon = "🦊"
flavor_icon = "🌿"
inspiration = "https://github.com/EdenEast/nightfox.nvim"

[colors]
# === Core Text Colors ===
text_primary = "#e6eaea" # Primary text throughout app
text_muted = "#7d8991"   # Muted text for help bar separators

# === Layout Colors ===
surface = "#2f3239" # Surface background for pickers

# === Accent Colors ===
primary_accent = "#7aa4a1" # Teal - focused borders, active states, status text
title_accent = "#e6eaea"   # Primary text - component titles
header_accent = "#8eb2af"  # Green - table headers and line numbers

# === Selection Colors ===
selection_bg = "#a78cfa" # Purple - selection background
selection_fg = "#152528" # Dark text - selection foreground

# === Message Table Colors ===
message_sequence = "#fda47f"       # Orange - sequence numbers
message_id = "#ff8a95"             # Pink - message identifiers
message_timestamp = "#7aa4a1"      # Teal - timestamps
message_delivery_count = "#a78cfa" # Purple - delivery counts
message_state_ready = "#8eb2af"    # Green - Ready for delivery (Active, Scheduled)
message_state_deferred = "#fda47f" # Orange - Deferred handling (Deferred)
message_state_outcome = "#a78cfa"  # Purple - Processing outcome (Completed, Abandoned)
message_state_failed = "#ff8a95"   # Pink - Failed delivery (Dead-lettered)
queue_count = "#8eb2af"            # Green - for queue counts (legacy field)

# === List Item Colors ===
namespace_list_item = "#a78cfa" # Purple - namespace picker items

# === Status Colors ===
status_success = "#8eb2af" # Green - success messages
status_warning = "#fda47f" # Orange - warning messages
status_error = "#ff8a95"   # Pink - error messages
status_info = "#7aa4a1"    # Teal - queue picker items
status_loading = "#a78cfa" # Purple - loading indicator

# === Help System Colors ===
shortcut_key = "#fda47f"         # Orange - keyboard shortcuts
shortcut_description = "#7d8991" # Muted text - help descriptions
help_section_title = "#a78cfa"   # Purple - help section titles

# === Popup System Colors (used by confirmation popup) ===
popup_background = "#0f1c1e" # Slightly different from main bg
popup_text = "#7d8991"       # Muted text - secondary text
