[package]
name = "server"
version = "0.1.0"
edition = "2024"

[lib]
name = "server"
path = "src/lib.rs"

[dependencies]
tokio = { version = "1.45.0", features = ["rt-multi-thread", "macros"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
azservicebus = "0.20.4"
azure_core = "0.24.0"
uuid = { version = "1", features = ["v4"] }
chrono = "0.4"
