# Catppuccin Mocha - The Original — Our darkest variant offering a cozy feeling with color-rich accents
[metadata]
name = "Catppuccin Mocha"
description = "The Original — Our darkest variant offering a cozy feeling with color-rich accents"
author = "Catppuccin Community"
theme_name = "catppuccin"
flavor_name = "mocha"
theme_icon = "😸"
flavor_icon = "🌿"
inspiration = "https://github.com/catppuccin/catppuccin"

[colors]
# === Core Text Colors ===
text_primary = "#cdd6f4" # Text - primary text throughout app
text_muted = "#a6adc8"   # Subtext0 - help bar separators

# === Layout Colors ===
surface = "#313244" # Surface0 - background for pickers

# === Accent Colors ===
primary_accent = "#89b4fa" # Blue - focused borders, active states, status text
title_accent = "#cdd6f4"   # Text - component titles
header_accent = "#a6e3a1"  # Green - table headers and line numbers

# === Selection Colors ===
selection_bg = "#cba6f7" # Mauve - selection background
selection_fg = "#1e1e2e" # Base - selection foreground

# === Message Table Colors ===
message_sequence = "#f9e2af"       # Yellow - sequence numbers
message_id = "#f38ba8"             # Red - message identifiers
message_timestamp = "#89dceb"      # Sky - timestamps
message_delivery_count = "#cba6f7" # Mauve - delivery counts
message_state_ready = "#a6e3a1"    # Green - Ready for delivery (Active, Scheduled)
message_state_deferred = "#f9e2af" # Yellow - Deferred handling (Deferred)
message_state_outcome = "#cba6f7"  # Mauve - Processing outcome (Completed, Abandoned)
message_state_failed = "#f38ba8"   # Red - Failed delivery (Dead-lettered)
queue_count = "#a6e3a1"            # Green - for queue counts (legacy field)

# === List Item Colors ===
namespace_list_item = "#cba6f7" # Mauve - namespace picker items

# === Status Colors ===
status_success = "#a6e3a1" # Green - success messages
status_warning = "#f9e2af" # Yellow - warning messages
status_error = "#f38ba8"   # Red - error messages
status_info = "#89dceb"    # Sky - queue picker items
status_loading = "#cba6f7" # Mauve - loading indicator

# === Help System Colors ===
shortcut_key = "#f9e2af"         # Yellow - keyboard shortcuts
shortcut_description = "#a6adc8" # Subtext0 - help descriptions
help_section_title = "#cba6f7"   # Mauve - help section titles

# === Popup System Colors (used by confirmation popup) ===
popup_background = "#181825" # Mantle - slightly different from main bg
popup_text = "#a6adc8"       # Subtext0 - secondary text
