# A sleek dark theme for Quetty with excellent contrast and readability
[metadata]
name = "Quetty Dark"
description = "A sleek dark theme for Quetty with excellent contrast and readability"
author = "Dawid Pereira"
theme_name = "quetty"
flavor_name = "dark"
theme_icon = "⚡"
flavor_icon = "🌙"

[colors]
# === Core Text Colors ===
text_primary = "#c0caf5" # Bright blue-white - primary text throughout app
text_muted = "#565f89"   # Subtle gray-blue - help bar separators

# === Layout Colors ===
surface = "#24283b" # Slightly lighter surface - background for pickers

# === Accent Colors ===
primary_accent = "#7aa2f7" # Bright blue - focused borders, active states, status text
title_accent = "#c0caf5"   # Bright blue-white - component titles
header_accent = "#9ece6a"  # Fresh green - table headers and line numbers

# === Selection Colors ===
selection_bg = "#bb9af7" # Bright purple - selection background
selection_fg = "#1a1b26" # Dark text - selection foreground

# === Message Table Colors ===
message_sequence = "#e0af68"       # Golden yellow - sequence numbers  
message_id = "#f7768e"             # Warm coral - message identifiers
message_timestamp = "#7dcfff"      # Light cyan - timestamps
message_delivery_count = "#bb9af7" # Purple - delivery counts
message_state_ready = "#9ece6a"    # Fresh green - Ready for delivery (Active, Scheduled)
message_state_deferred = "#e0af68" # Warm yellow - Deferred handling (Deferred)
message_state_outcome = "#bb9af7"  # Purple - Processing outcome (Completed, Abandoned)
message_state_failed = "#f7768e"   # Soft red - Failed delivery (Dead-lettered)
queue_count = "#9ece6a"            # Fresh green - for queue counts (legacy field)

# === List Item Colors ===
namespace_list_item = "#bb9af7" # Soft purple - namespace picker items

# === Status Colors ===
status_success = "#9ece6a" # Fresh green - success messages
status_warning = "#e0af68" # Warm yellow - warning messages
status_error = "#f7768e"   # Soft red - error messages
status_info = "#7dcfff"    # Light cyan - queue picker items
status_loading = "#bb9af7" # Purple - loading indicator

# === Help System Colors ===
shortcut_key = "#e0af68"         # Yellow - keyboard shortcuts
shortcut_description = "#9aa5ce" # Muted blue-gray - help descriptions
help_section_title = "#bb9af7"   # Purple - help section titles

# === Popup System Colors (used by confirmation popup) ===
popup_background = "#1f2335" # Slightly different from main bg
popup_text = "#9aa5ce"       # Secondary text
