name: Build

on:
  push:
    branches: [ "main" ]
    paths:
      - 'server/**'
      - 'ui/**'
      - 'Cargo.*'
      - '.github/workflows/build.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'server/**'
      - 'ui/**'
      - 'Cargo.*'
      - '.github/workflows/build.yml'
  workflow_call:
    outputs:
      cache-key:
        description: "Cargo cache key for this build"
        value: ${{ jobs.build.outputs.cache-key }}

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache.outputs.cache-primary-key }}

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        components: rustfmt, clippy

    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    - name: Cache Cargo dependencies
      id: cache
      uses: Swatinem/rust-cache@v2
      with:
        shared-key: "build-cache"

    - name: Build workspace
      run: cargo build --verbose

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          target/debug/
          !target/debug/incremental
          !target/debug/build
          !target/debug/.fingerprint
        retention-days: 1
