name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        components: rustfmt, clippy

    - name: Cache Cargo dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Build
      run: cargo build --verbose

    - name: Copy example config.toml for tests
      run: cp ui/config.example.toml config.toml

    - name: Run tests
      run: cargo test --verbose

    - name: Check formatting
      run: cargo fmt --check

    - name: Run Clippy
      run: cargo clippy --workspace --all-features -- -D warnings

  notify-on-failure:
    runs-on: ubuntu-latest
    needs: build
    if: failure()

    steps:
    - name: Send failure notification to Notion
      env:
        NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
        NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
      run: |
        PAYLOAD=''{ "parent": { "database_id": "'"$NOTION_DATABASE_ID"'" }, "properties": { "Title": { "title": [ { "text": { "content": "Bug - Quetty - CI Build Failed: ${{ github.repository }} - ${{ github.ref_name }}" } } ] }, "Status": { "select": { "name": "Not Started" } }, "Priority": { "select": { "name": "Medium" } }, "Type": { "select": { "name": "Bug" } }, "Project": { "select": { "name": "Quetty" } }, "Archived": { "checkbox": false } } }''

        curl -X POST "https://api.notion.com/v1/pages" \
          -H "Authorization: Bearer $NOTION_API_TOKEN" \
          -H "Content-Type: application/json" \
          -H "Notion-Version: 2022-06-28" \
          -d "$PAYLOAD"
