name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        components: rustfmt, clippy

    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    - name: Check disk space before build
      run: df -h

    - name: Cache Cargo dependencies
      uses: Swatinem/rust-cache@v2
      with:
        shared-key: "ci-cache"

    - name: Build
      run: cargo build --verbose

    - name: Check disk space after build
      run: df -h

    - name: Copy default config files for tests
      run: |
        cp config.default.toml config.toml
        cp keys.default.toml keys.toml

    - name: Run tests
      run: cargo test --verbose

    - name: Check disk space after tests
      run: df -h

    - name: Check formatting
      run: cargo fmt --check

    - name: Clean build artifacts before clippy
      run: cargo clean

    - name: Run Clippy
      run: cargo clippy --workspace --all-features -- -D warnings

    - name: Check final disk space
      run: df -h

  call-notion-notification:
    needs: build
    if: failure()
    uses: ./.github/workflows/notion-notification.yml
    with:
      repository: ${{ github.repository }}
      ref_name: ${{ github.ref_name }}
      run_id: ${{ github.run_id }}
    secrets:
      NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
      NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
