name: Lint

on:
  push:
    branches: [ "main" ]
    paths:
      - 'server/**'
      - 'ui/**'
      - 'Cargo.*'
      - '.github/workflows/lint.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'server/**'
      - 'ui/**'
      - 'Cargo.*'
      - '.github/workflows/lint.yml'
  workflow_call:

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        components: rustfmt

    - name: Check formatting
      run: cargo fmt --check

  clippy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        components: clippy

    - name: Cache Cargo dependencies
      uses: Swatinem/rust-cache@v2
      with:
        shared-key: "lint-cache"

    - name: Run Clippy
      run: cargo clippy --workspace --all-features -- -D warnings
