name: Notion Notification

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      ref_name:
        required: true
        type: string
      run_id:
        required: true
        type: string
    secrets:
      NOTION_API_TOKEN:
        required: true
      NOTION_DATABASE_ID:
        required: true

jobs:
  notify-on-failure:
    runs-on: ubuntu-latest

    steps:
    - name: Send failure notification to Notion
      env:
        NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
        NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        GH_REPOSITORY: ${{ inputs.repository }}
        GH_REF_NAME: ${{ inputs.ref_name }}
        GH_RUN_ID: ${{ inputs.run_id }}
      shell: bash
      run: |
        PAYLOAD=$(cat <<'EOF'
        {
          "parent": {
            "database_id": "$NOTION_DATABASE_ID"
          },
          "properties": {
            "Title": {
              "title": [
                {
                  "text": {
                    "content": "Bug - Quetty - CI Build Failed: $GH_REPOSITORY - $GH_REF_NAME"
                  }
                }
              ]
            },
            "Status": {
              "select": {
                "name": "Not Started"
              }
            },
            "Priority": {
              "select": {
                "name": "Medium"
              }
            },
            "Type": {
              "select": {
                "name": "Bug"
              }
            },
            "Project": {
              "select": {
                "name": "Quetty"
              }
            },
            "Archived": {
              "checkbox": false
            }
          }
        }
        EOF
        )

        # Substitute environment variables in the payload
        PAYLOAD=$(echo "$PAYLOAD" | envsubst)

        echo "Sending payload to Notion:"
        echo "$PAYLOAD"

        RESPONSE=$(curl -s -w "\n%{http_code}" -X POST "https://api.notion.com/v1/pages" \
          -H "Authorization: Bearer $NOTION_API_TOKEN" \
          -H "Content-Type: application/json" \
          -H "Notion-Version: 2022-06-28" \
          -d "$PAYLOAD")

        HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
        BODY=$(echo "$RESPONSE" | head -n -1)

        echo "HTTP Status Code: $HTTP_CODE"
        echo "Response Body: $BODY"

        if [ "$HTTP_CODE" -ge 200 ] && [ "$HTTP_CODE" -lt 300 ]; then
          echo "Successfully sent notification to Notion"
        else
          echo "Failed to send notification to Notion"
          exit 1
        fi

