name: Notion Notification

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      ref_name:
        required: true
        type: string
      run_id:
        required: true
        type: string
    secrets:
      NOTION_API_TOKEN:
        required: true
      NOTION_DATABASE_ID:
        required: true

jobs:
  notify-on-failure:
    runs-on: ubuntu-latest

    steps:
    - name: Send failure notification to Notion
      env:
        NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
        NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
      run: |
        PAYLOAD=$(cat <<EOF
{
  "parent": {
    "database_id": "${{ env.NOTION_DATABASE_ID }}"
  },
  "properties": {
    "Title": {
      "title": [
        {
          "text": {
            "content": "Bug - Quetty - CI Build Failed: ${{ inputs.repository }} - ${{ inputs.ref_name }}"
          }
        }
      ]
    },
    "Status": {
      "select": {
        "name": "Not Started"
      }
    },
    "Priority": {
      "select": {
        "name": "Medium"
      }
    },
    "Type": {
      "select": {
        "name": "Bug"
      }
    },
    "Project": {
      "select": {
        "name": "Quetty"
      }
    },
    "Archived": {
      "checkbox": false
    }
  }
}
EOF
)

        curl -X POST "https://api.notion.com/v1/pages" -H "Authorization: Bearer ${{ env.NOTION_API_TOKEN }}" -H "Content-Type: application/json" -H "Notion-Version: 2022-06-28" -d "$PAYLOAD"
